name: date_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  awesome_top_snackbar: ^0.0.3
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

  path_provider: ^2.1.5
  file_picker: ^5.2.4
  image_preview: ^1.3.5
  google_fonts: ^6.2.1
  responsive_grid_list: ^1.4.0
  cached_network_image: ^3.4.1
  floating_action_bubble: ^1.1.4
  flutter_tilt: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
